name: Deploy Spring Boot Application

on:
  workflow_dispatch: # Allows manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Important for SonarQube analysis

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and Test
        run: |
          cd java-maven-sonar-argocd-helm-k8s/spring-boot-app
          mvn clean package

      - name: Static Code Analysis (SonarQube)
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_URL: "http://34.147.186.164:9000"
        run: |
          cd java-maven-sonar-argocd-helm-k8s/spring-boot-app
          mvn sonar:sonar \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.host.url=$SONAR_URL

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          cd java-maven-sonar-argocd-helm-k8s/spring-boot-app
          IMAGE_TAG="nwaykole25/cicd:${{ github.run_number }}"
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG

      - name: Update Deployment File
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} # Ensure this secret is created
        run: |
          git config --global user.email "nutanwaykole25@gmail.com"
          git config --global user.name "nwaykole"
          
          # Replace tag in deployment manifest
          sed -i "s/replaceImageTag/${{ github.run_number }}/g" java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml
          
          git add java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml
          git commit -m "Update deployment image to version ${{ github.run_number }}"
          git push origin HEAD:main